name: Update and Release Ansible galaxy collections

on:
  schedule:
    - cron: '0 3 * * *' # Запуск каждый день в 03:00 UTC
  workflow_dispatch: # Позволяет запустить вручную из интерфейса GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      
      - name: Download collections
        run: ansible-galaxy collection download -r requirements.yml -p offline-collections

      - name: Compress folder with tar
        run: tar -czf offline-collections.tar.gz ./offline-collections

      - uses: ncipollo/release-action@v1
        with:
          name: "Ansible galaxy offline collection ${{ steps.date.outputs.date }}"
          artifacts: "offline-collections.tar.gz"
          tag: "v${{ steps.date.outputs.date }}"
          bodyFile: ".github/release-body.md"
          allowUpdates: true
          makeLatest: true 

      - name: Update 'latest' git tag
        uses: EndBug/latest-tag@latest
        with:
          tag-name: latest
          description: Always points to the latest filter list release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
